---
title: "US Foreign Policy"
subtitle: "Class Introduction"
author: "Michael E. Flynn"
institute: "Kansas State University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "../../../styles/lecture_theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
      titleSlideClass: [middle, left, inverse]
---


# Welcome!

## Why this class matters:

- International relations affects your day to day life in so many ways

- Trade, migration, and investment

- War and conflict

- Global governance



---
class:left, top

# Details 


Class info:

- Class: US Foreign Policy

- Me: Michael Flynn

- Location: Online

- Time: MWF 12:30-1:20

- Office hours: By appointment

- Email! [meflynn@ksu.edu](mailto:meflynn@ksu.edu)


???

- Course Materials: [See the course page on my website](http://polsc343.m-flynn.com)








---
class: left, top

# Contacting Me

- The best way to contact me is email! (You can also schedule in-person appointments)

- Please, email me!

- Don't wait!



---
class: left, top

# Contacting Me

Some things to think about:

- All correspondence should be professional in tone (I'm not your "bro")

- Please address emails to "Professor Flynn" (Or something similar)

- Protip-All faculty and staff appreciate your efforts to be respectful and are *much* more likely to go the extra mile to help you out.


---
class: inverse, center, middle

# Stuff you need



---
class: left, top

# Stuff You Need

The syllabus---Read it!

Class format is both lecture and discussion

Required readings:

1. Brooks, R. 2017. How everything because war and the military became everything. Simon & Schuster.

2. Immerwahr, D. 2020. How to hide an empire. Picador. 

3. Alexander Cooley and Daniel Nexon. 2020. Exit from hegemony: The unraveling of the
American global order. Oxford University Press

4. Various articles (see syllabus)


---
class: left, top

# Requirements

<br>

```{r grade_breakdown, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
requirements <- tibble(`Grade Item` = c("Weekly Discussion", "Weekly Quizzes", "Weekly Blog", "Music of Foreign Policy Wiki"),
                       `Percent` = c("30%", "20%", "20%", "30%"))

knitr::kable(requirements, 'html', align = c("l", "c")) %>% 
  kable_styling(full_width=TRUE) %>% 
  column_spec(1, width_min = "10cm") %>%
  column_spec(2, width_min = "5cm") %>% 
  row_spec(0, bold = T, color = "white", background = "#512888")




```


---
class:left, top

# Academic Dishonesty and Plagiarism

Things to know:

- Don't do it

- Yes, we can tell

- You will fail the assignment

  - Possible the whole course

    - Maybe suspension, too
    
- See the syllabus for more information

- Also see [K-State's student handbook](https://www.k-state.edu/disclosures/handbooks.html) online


---
class: left, top

# Classroom Conduct

1. Be Kind

2. Please make sure your questions and comments pertain to course materials

3. Be respectful of one another in your discussions

4. Reach out if you need help, and reach out early


---
class: inverse, center, middle

# Big Picture Preview


---
class: left, top

# Myths of US Foreign Policy

1. The "national interest"

2. Politics stops at the water's edge

3. Isolationism vs. internationalism

4. "Grand strategy"


